/*Table Owner*/
CREATE TABLE FARM_CLIENT(
ID INTEGER PRIMARY KEY,
Proprietaire VARCHAR(10),
Courriel VARCHAR(40),
);
GO

/*Table Farm*/
CREATE TABLE FARM(
ID INTEGER PRIMARY KEY,
Nom VARCHAR(40),
Proprietaire INT FOREIGN KEY REFERENCES FARM_CLIENT(ID),
Addresse VARCHAR(40),
Superficie INT,
);
Go

/*Table Crop*/
CREATE TABLE CROP(
ID INTEGER PRIMARY KEY,
Nom VARCHAR(10),
"Type" VARCHAR(40),
"Location" INT FOREIGN KEY REFERENCES FARM(ID),
);
GO

/*Table HARVEST*/
CREATE TABLE Harvest(
ID INTEGER PRIMARY KEY,
QTY INT,
Proprietaire INT FOREIGN KEY REFERENCES FARM_CLIENT(ID),
);
GO